force-app/main/default/objects/Bus_Route__c/Bus_Route__c.object-meta.xml
<CustomObject>
    <label>Bus Route</label>
    <nameField>
        <label>Bus Route Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Bus Routes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Bus_Route__c/fields/Duration_In_Minutes__c.field-meta.xml
<CustomField>
    <fullName>Duration_In_Minutes__c</fullName>
    <formula>(  HOUR( End_Time__c ) - HOUR(Start_Time__c)) *60 
+(  MINUTE( End_Time__c ) - MINUTE(Start_Time__c )  )</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Duration In Minutes</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Bus_Route__c/fields/Name__c.field-meta.xml
<CustomField>
    <fullName>Name__c</fullName>
    <displayFormat>BR-{0000}</displayFormat>
    <label>Name</label>
    <type>AutoNumber</type>
</CustomField>

force-app/main/default/objects/Bus_Route__c/fields/Total_Stops__c.field-meta.xml
<CustomField>
    <fullName>Total_Stops__c</fullName>
    <description>Calculates total number of bus stops in a route</description>
    <label>Total Stops</label>
    <summaryForeignKey>Bus_Stop__c.Bus_Route__c</summaryForeignKey>
    <summaryOperation>count</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/objects/Bus_Stop__c/Bus_Stop__c.object-meta.xml
<CustomObject>
    <description>Bus stop. May be a lot of stops in the route.</description>
    <label>Bus Stop</label>
    <nameField>
        <label>Bus Stop Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Bus Stops</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Bus_Stop__c/fields/Bus_Route__c.field-meta.xml
<CustomField>
    <fullName>Bus_Route__c</fullName>
    <label>Bus Route</label>
    <referenceTo>Bus_Route__c</referenceTo>
    <relationshipLabel>Bus Stops</relationshipLabel>
    <relationshipName>Bus_Stops</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Schedule__c/Schedule__c.object-meta.xml
<CustomObject>
    <description>Time for every route on every stop.</description>
    <label>Schedule</label>
    <nameField>
        <label>Schedule Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Schedules</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Schedule__c/fields/Bus_Route__c.field-meta.xml
<CustomField>
    <fullName>Bus_Route__c</fullName>
    <label>Bus Route</label>
    <referenceTo>Bus_Route__c</referenceTo>
    <relationshipLabel>Schedules</relationshipLabel>
    <relationshipName>Schedules</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Schedule__c/fields/Bus_Stop__c.field-meta.xml
<CustomField>
    <fullName>Bus_Stop__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Bus Stop</label>
    <referenceTo>Bus_Stop__c</referenceTo>
    <relationshipLabel>Schedules</relationshipLabel>
    <relationshipName>Schedules</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Schedule__c/fields/Name__c.field-meta.xml
<CustomField>
    <fullName>Name__c</fullName>
    <displayFormat>S-{0000}</displayFormat>
    <label>Name</label>
    <type>AutoNumber</type>
</CustomField>

force-app/main/default/classes/TransportDAO.cls
public with sharing class TransportDAO {
    
    //Get number of bus stops by bus route Id
   public static Integer getNumberOfStops(Id busRouteId) {

       Bus_Route__c route = [SELECT Total_Stops__c FROM Bus_Route__c WHERE Id =: busRouteId];

       return Integer.valueOf(route.Total_Stops__c);

   }
    //System.debug(TransportDAO.getNumberOfStops('a007Q00000BHdypQAD'));

    //Get Id of longest by time route
    public static Id getLongestByTimeRouteId() {

        List<Bus_Route__c> listRoutes = [SELECT Id FROM Bus_Route__c ORDER BY Duration_In_Minutes__c DESC LIMIT 1];

        Bus_Route__c route = listRoutes.get(0);

        return  route.Id;
        
    }
    //System.debug(TransportDAO.getLongestByTimeRouteId());

     //Get list of bus schedtules
    public static List<Schedule__c> getSchedules(Integer limitNumber, Integer offsetNumber) {

        List<Schedule__c> listSchedule = new List<Schedule__c>();

        if ((offsetNumber > 0)&&(limitNumber > offsetNumber)) {
            listSchedule = [SELECT Name FROM Schedule__c LIMIT :limitNumber OFFSET :offsetNumber];
        } else {
            System.debug('Invalid parameters');
        }
       
        return listSchedule;

    }
   // System.debug(TransportDAO.getSchedules(3, 1));


    public static List<Bus_Stop__c> getBusStopsByIds(Set<Id> busStops) {
        //Get list of bus stops by bus stop Ids
       // List<Bus_Stop__c> listStops = [SELECT Name FROM Bus_Stop__c WHERE Id IN: busStops];
        
        return [SELECT Name FROM Bus_Stop__c WHERE Id IN: busStops];
    }
    // Set<Id> s1 = new Set<Id>();
    // s1.add('a017Q000019IilYQAS');
    // s1.add('a017Q000019Jin4QAC');
    // System.debug(TransportDAO.getBusStopsByIds(s1));

   public static List<Bus_Route__c> getBusRoutes (Set<Id> busStops) {
        //Get list of bus routes for specified set of bus stops
     //   List<Bus_Stop__c> listStops = [SELECT Bus_Route__c FROM Bus_Stop__c WHERE Id IN: busStops];

        Set<Id> setRoutes = new Set<Id>();

        for (Schedule__c i : [SELECT Bus_Route__c FROM Schedule__c WHERE 	Bus_Stop__c IN: busStops]) {

            setRoutes.add(i.Bus_Route__c);
            
        }

       // List<Bus_Route__c> listRoutes = [SELECT Name__c FROM Bus_Route__c WHERE Id IN: setRoutes];

       return [SELECT Name__c FROM Bus_Route__c WHERE Id IN: setRoutes];
   }

    public static Map<Id, Integer> getBusRoutesWithMinDuration(Integer limitNumber) {
        //Returns map of bus route to duration. Parameter limit specifies number of shortest routes which should be returned

        Map<Id, Integer> routeTime = new Map<Id, Integer>();

        for (Bus_Route__c item : [SELECT Id, Duration_In_Minutes__c FROM Bus_Route__c ORDER BY Duration_In_Minutes__c ASC LIMIT :limitNumber ]) {
            routeTime.put(item.Id, Integer.valueOf(item.Duration_In_Minutes__c));
        }

        return routeTime;
    }

   //System.debug(TransportDAO.getBusRoutesWithMinDuration(1));


    public static Map<Id, Integer> getBusRoutesWithMaxDuration(Integer limitNumber) {
        //  Returns map of bus route to duration. Parameter limit specifies number of longest routes which should be returned

        Map<Id, Integer> routeTime = new Map<Id, Integer>();

        for (Bus_Route__c i : [SELECT Id, Duration_In_Minutes__c FROM Bus_Route__c ORDER BY Duration_In_Minutes__c DESC LIMIT :limitNumber ]) {
            routeTime.put(i.Id, Integer.valueOf(i.Duration_In_Minutes__c));
        }

        return routeTime;
    }

    //System.debug(TransportDAO.getBusRoutesWithMaxDuration(1));
}