force-app/main/default/objects/Bus_Route__c/Bus_Route__c.object-meta.xml
<CustomObject>
    <label>Bus Route</label>
    <nameField>
        <label>Bus Route Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Bus Routes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Bus_Route__c/fields/Route_Description__c.field-meta.xml
<CustomField>
    <fullName>Route_Description__c</fullName>
    <label>Route Description</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Bus_Stop__c/Bus_Stop__c.object-meta.xml
<CustomObject>
    <description>Bus stop. May be a lot of stops in the route.</description>
    <label>Bus Stop</label>
    <nameField>
        <label>Bus Stop Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Bus Stops</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Bus_Stop__c/fields/Bus_Route__c.field-meta.xml
<CustomField>
    <fullName>Bus_Route__c</fullName>
    <label>Bus Route</label>
    <referenceTo>Bus_Route__c</referenceTo>
    <relationshipLabel>Bus Stops</relationshipLabel>
    <relationshipName>Bus_Stops</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Schedule__c/Schedule__c.object-meta.xml
<CustomObject>
    <description>Time for every route on every stop.</description>
    <label>Schedule</label>
    <nameField>
        <label>Schedule Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Schedules</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Schedule__c/fields/Bus_Route__c.field-meta.xml
<CustomField>
    <fullName>Bus_Route__c</fullName>
    <label>Bus Route</label>
    <referenceTo>Bus_Route__c</referenceTo>
    <relationshipLabel>Schedules</relationshipLabel>
    <relationshipName>Schedules</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Schedule__c/fields/Bus_Stop__c.field-meta.xml
<CustomField>
    <fullName>Bus_Stop__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Bus Stop</label>
    <referenceTo>Bus_Stop__c</referenceTo>
    <relationshipLabel>Schedules</relationshipLabel>
    <relationshipName>Schedules</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/RouteDescriptionBatch.cls
public with sharing class RouteDescriptionBatch implements Database.Batchable<sObject>, Schedulable,  Database.Stateful {
    
    public Database.QueryLocator start (Database.BatchableContext bc) {
        return Database.getQueryLocator(
            'SELECT id, Route_Description__c, (SELECT Time__c, Bus_Stop__r.Address__c FROM Schedules__r ORDER BY Time__c ASC) FROM Bus_Route__c' 
        );
    }

    public void execute(Database.BatchableContext bc, list<Bus_Route__c> routesList){

        for (Bus_Route__c route: routesList){
            route.Route_Description__c = '';
            for (Schedule__c schedule : route.Schedules__r) {
                route.Route_Description__c = route.Route_Description__c + schedule.Bus_Stop__r.Address__c + ' - ';
            }
        }

        update routesList;

    }

    public void finish(Database.BatchableContext bc){}

    public void execute(SchedulableContext pr1){
        RouteDescriptionBatch routeDescription = new RouteDescriptionBatch();
        Id batchId = Database.executeBatch(routeDescription);
    }

}


//Database.executeBatch(new RouteDescriptionBatch(), 200);