force-app/main/default/objects/Bus_Route__c/Bus_Route__c.object-meta.xml
<CustomObject>
    <label>Bus Route</label>
    <nameField>
        <label>Bus Route Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Bus Routes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Bus_Route__c/fields/End_Time__c.field-meta.xml
<CustomField>
    <fullName>End_Time__c</fullName>
    <description>End Time of the Route</description>
    <label>End Time</label>
    <type>Time</type>
</CustomField>

force-app/main/default/objects/Bus_Route__c/fields/Start_Time__c.field-meta.xml
<CustomField>
    <fullName>Start_Time__c</fullName>
    <description>Start Time of the Route</description>
    <label>Start Time</label>
    <type>Time</type>
</CustomField>

force-app/main/default/objects/Schedule__c/Schedule__c.object-meta.xml
<CustomObject>
    <description>Time for every route on every stop.</description>
    <label>Schedule</label>
    <nameField>
        <label>Schedule Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Schedules</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Schedule__c/fields/Bus_Route__c.field-meta.xml
<CustomField>
    <fullName>Bus_Route__c</fullName>
    <label>Bus Route</label>
    <referenceTo>Bus_Route__c</referenceTo>
    <relationshipLabel>Schedules</relationshipLabel>
    <relationshipName>Schedules</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Schedule__c/fields/Time_To_Next_Stop__c.field-meta.xml
<CustomField>
    <fullName>Time_To_Next_Stop__c</fullName>
    <description>Time in minutes to the next stop in a route.</description>
    <label>Time To Next Stop</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/ScheduleTriggerHandler.cls
public with sharing class ScheduleTriggerHandler {
    //Start and End Times of the Bus Route should be based on the minimum and maximum values in the Time field of the Schedule.
    //after Insert update sch
    public static void updateStartEndTime(List<Schedule__c> newSchedules, Map<Id, Schedule__c> oldSchedulesMap){

        Set<Id> idsSet = new Set<Id>();

        if (oldSchedulesMap == null) {
            //insert new sch
            for(Schedule__c schedule : newSchedules){
                idsSet.add(schedule.Bus_Route__c);
            }
            
        }else{
            //update time or bus route in sch
            for (Schedule__c sch : newSchedules) {
                if (sch.Time__c != oldSchedulesMap.get(sch.Id).Time__c || sch.Bus_Route__c != oldSchedulesMap.get(sch.Id).Bus_Route__c) {
                    idsSet.add(sch.Bus_Route__c);
                    idsSet.add(oldSchedulesMap.get(sch.Id).Bus_Route__c);
                }
            }
        }

        if (idsSet == null) {
            return ;
        }

        List <Bus_Route__c> busRouteList = [SELECT Start_Time__c, End_Time__c, 
                (SELECT Time__c FROM Schedules__r ORDER BY Time__c ASC) 
                FROM Bus_Route__c WHERE Id IN: idsSet];

        for (Bus_Route__c br : busRouteList) {
            If (!br.Schedules__r.isEmpty()) {
                br.Start_Time__c = br.Schedules__r.get(0).Time__c;
                br.End_Time__c = br.Schedules__r.get(br.Schedules__r.size()-1).Time__c;
            }
        }
            
        update busRouteList;

    }

    // автоматично прокалькулювати TimeToNextStop__c 
    //це має бути на інсерті Schedule__c або на апдейті Schedule__c поля BusRoute__c або поля BusStop__c або поля Time__c
    public static void setTimeToNextStop(List<Schedule__c> newSchedules, Map<Id, Schedule__c> oldSchedulesMap) {

        Set<Id> idsSetRoute = new Set<Id>();

        if (oldSchedulesMap == null) {
            //insert new sch
            for(Schedule__c schedule : newSchedules){
                idsSetRoute.add(schedule.Bus_Route__c);
            }
            
        }else{
            //update time or bus route in sch
            for (Schedule__c sch : newSchedules) {
                if (sch.Time__c != oldSchedulesMap.get(sch.Id).Time__c || sch.Bus_Route__c != oldSchedulesMap.get(sch.Id).Bus_Route__c) {
                    idsSetRoute.add(sch.Bus_Route__c);
                    idsSetRoute.add(oldSchedulesMap.get(sch.Id).Bus_Route__c);
                }
            }
        }

        if (idsSetRoute == null) {
            return ;
        }

        List<Bus_Route__c> busRouteList = [
                SELECT Start_Time__c, End_Time__c, 
                (SELECT Time__c, Time_To_Next_Stop__c FROM Schedules__r ORDER BY Time__c ASC) 
                FROM Bus_Route__c 
                WHERE Id 
                IN: idsSetRoute];

        List<Schedule__c> schedtoUpdate = new List<Schedule__c>();

        for (Bus_Route__c br : busRouteList) {
            for ( Integer i = 0; i <  br.Schedules__r.size(); i++ ) {
                //остання зупинки, де час до наступної = 0
                if (i == (br.Schedules__r.size() - 1)) {
                    br.Schedules__r.get(i).Time_To_Next_Stop__c = 0;
                }else{
                    br.Schedules__r.get(i).Time_To_Next_Stop__c =
                     (br.Schedules__r.get(i+1).Time__c.hour() - br.Schedules__r.get(i).Time__c.hour())*60 + (br.Schedules__r.get(i+1).Time__c.minute() - br.Schedules__r.get(i).Time__c.minute());
                }
            schedtoUpdate.add(br.Schedules__r.get(i));
        }

        update schedtoUpdate;

    }
}

}